name: Mirror to Codeberg

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history to push tags

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Codeberg remote
        run: |
          git remote add codeberg https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/gmodena/landingtree.git

      - name: Push to Codeberg
        run: |
          git push --mirror codeberg
